# docker-compose build
version: '3.9'
volumes:
  dbbackups:
  postgis-data:

services:

  db:
    image: kartoza/postgis:14-3.2
    shm_size: 1g
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - envs.env
    ports:
      - "25432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  app:
    image: api/button-recorder:0.0
    ports:
      - "8000:8000"
    env_file:
      - envs.env

  dbbackups:
    image: kartoza/pg-backup:14-3.2
    hostname: pg-backups
    volumes:
      - dbbackups:/backups
    env_file:
      - envs.env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
